# frozen_string_literal: true

#
# Cookbook Name:: resource_router
# Recipe:: routing
#
# Copyright 2017, P. van der Velde
#

#
# INSTALL QUAGGA
#

apt_package 'quagga' do
  action :install
  version '0.99.24.1-2ubuntu1'
end

# Make sure the quagga service doesn't start automatically. This will be changed
# after we have provisioned the box
service 'quagga' do
  action :disable
end

#
# CONFIGURE QUAGGA
#

file '/etc/quagga/daemon' do
  action :create
  content <<~CONF
    # This file tells the quagga package which daemons to start.
    #
    # Entries are in the format: <daemon>=(yes|no|priority)
    #   0, "no"  = disabled
    #   1, "yes" = highest priority
    #   2 .. 10  = lower priorities
    # Read /usr/share/doc/quagga/README.Debian for details.
    #
    # Sample configurations for these daemons can be found in
    # /usr/share/doc/quagga/examples/.
    #
    # ATTENTION:
    #
    # When activation a daemon at the first time, a config file, even if it is
    # empty, has to be present *and* be owned by the user and group "quagga", else
    # the daemon will not be started by /etc/init.d/quagga. The permissions should
    # be u=rw,g=r,o=.
    # When using "vtysh" such a config file is also needed. It should be owned by
    # group "quaggavty" and set to ug=rw,o= though. Check /etc/pam.d/quagga, too.
    #
    # The watchquagga daemon is always started. Per default in monitoring-only but
    # that can be changed via /etc/quagga/debian.conf.
    #
    zebra=yes
    bgpd=yes
    ospfd=no
    ospf6d=no
    ripd=no
    ripngd=no
    isisd=no
    babeld=no
  CONF
end

file '/etc/quagga/debian.conf' do
  action :create
  content <<~CONF
    #
    # If this option is set the /etc/init.d/quagga script automatically loads
    # the config via "vtysh -b" when the servers are started.
    # Check /etc/pam.d/quagga if you intend to use "vtysh"!
    #
    vtysh_enable=yes
    zebra_options="  --daemon -A 127.0.0.1"
    bgpd_options="   --daemon -A 127.0.0.1"
    ospfd_options="  --daemon -A 127.0.0.1"
    ospf6d_options=" --daemon -A ::1"
    ripd_options="   --daemon -A 127.0.0.1"
    ripngd_options=" --daemon -A ::1"
    isisd_options="  --daemon -A 127.0.0.1"
    babeld_options=" --daemon -A 127.0.0.1"
    #
    # Please note that watchquagga_options is an array and not a string so that
    # quotes can be used.
    #
    # The list of daemons to watch is automatically generated by the init script
    # from daemons.conf and appended to the watchquagga_options.
    # Example:
    #    watchquagga_options=("-Adz" "-r" '/sbin/service %s restart' -s '/sbin/service %s start'  -k '/sbin/service %s stop')
    watchquagga_enable=yes
    watchquagga_options=(--daemon)
  CONF
end

file '/etc/quagga/zebra.conf' do
  action :create
  content <<~CONF
    ! -*- zebra -*-
    !
    ! zebra sample configuration file
    !
    ! $Id: zebra.conf.sample,v 1.1 2002/12/13 20:15:30 paul Exp $
    !
    hostname Router
    password zebra
    enable password zebra
    !
    ! Interface's description.
    !
    !interface lo
    ! description test of desc.
    !
    !interface sit0
    ! multicast

    !
    ! Static default route sample.
    !
    !ip route 0.0.0.0/0 203.181.89.241
    !

    !log file /var/log/quagga/zebra.log
  CONF
  group 'quagga'
  mode '0640'
  owner 'quagga'
end

#
# CONFIGURE BGP
#

# For the private use AS reservations see: https://tools.ietf.org/html/rfc6996
# Using some random number from the 32-bit Autonomous System Numbers ranging
# from 4200000000 - 4294967294
file '/etc/quagga/bgpd.conf' do
  action :create
  content <<~CONF
    ! -*- bgp -*-
    !
    ! BGPd sample configuration file
    !
    ! $Id: bgpd.conf.sample,v 1.1 2002/12/13 20:15:29 paul Exp $
    !
    hostname bgpd
    password zebra
    !enable password please-set-at-here
    !
    !bgp multiple-instance
    !
    router bgp 4212345678
    ! bgp router-id 10.0.0.1
    ! network 10.0.0.0/8
    ! neighbor 10.0.0.2 remote-as 7675
    ! neighbor 10.0.0.2 route-map set-nexthop out
    ! neighbor 10.0.0.2 ebgp-multihop
    ! neighbor 10.0.0.2 next-hop-self
    !
    ! access-list all permit any
    !
    !route-map set-nexthop permit 10
    ! match ip address all
    ! set ip next-hop 10.0.0.1
    !
    !log file /var/log/quagga/bgpd.log
    !
    log stdout
  CONF
  group 'quagga'
  mode '0640'
  owner 'quagga'
end

#
# CONFIGURE OSPF
#

file '/etc/quagga/ospfd.conf' do
  action :create
  content <<~CONF
    ! -*- ospf -*-
    !
    ! OSPFd sample configuration file
    !
    !
    hostname ospfd
    password zebra
    !enable password please-set-at-here
    !
    !router ospf
    !  network 192.168.1.0/24 area 0
    !
    log stdout
  CONF
  group 'quagga'
  mode '0640'
  owner 'quagga'
end

# Next make sure to forward traffic from Quagga over your ethernet device, otherwise this will not work!
file '/proc/sys/net/ipv4/ip_forward' do
  action :create
  content <<~CONF
    1
  CONF
end
